export const dataGuest = [
    {
        id: 8,
        fullName: 'Radovan Radic',
        email: 'radovanradic1@gmail.com',
        nationality: 'Serbian',
        nationalID: 'SRB',
        country: 'srb',
     }, 
    {
        id:3,
        fullName: 'John McEnrol',
        email: 'johnmcenrol1@gmail.com',
        nationality: 'Canadian',
        nationalID: '139445',
        country: 'Canada',
     }, 
    {
        id:2,
        fullName: 'Stipe Antic',
        email: 'stipeantic1@gmail.com',
        nationality: 'Croatian',
        nationalID: '064946',
        country: 'Croatia',
     }, 
    {
        id:1,
        fullName: 'Stipe Antic',
        email: 'stipeantic1@gmail.com',
        nationality: 'Croatian',
        nationalID: '064946',
        country: 'Croatia',
     }, 
    {
        id:5,
        fullName: 'Vladimir Petrovic',
        email: 'vladimirpetrovic2@gmail.com',
        nationality: 'Bulgarian',
        nationalID: '356464',
        country: 'Bulgaria',
     }, 
    {
        id:4,
        fullName: 'Zher Haren',
        email: 'zherHarem312@gmail.com',
        nationality: 'Hungarian',
        nationalID: '892389',
        country: 'Hungary',
     }, 
    {
        id:7,
        fullName: 'Petre Smith',
        email: 'petresmith321@gmail.com',
        nationality: 'Frenc',
        nationalID: '20954',
        country: 'France',
     }, 
    {
        id:6,
        fullName: 'Auger Nadal',
        email: 'augernadal29@gmail.com',
        nationality: 'Spanich',
        nationalID: '091256',
        country: 'Spain',
     }, 
    {
        id:9,
        fullName: 'Bautisa Agut',
        email: 'bautistaAgut994@gmail.com',
        nationality: 'Portuguese',
        nationalID: '0912356',
        country: 'Portugal',
     }, 
    {
        id:10,
        fullName: 'Milan Jokic',
        email: 'milanjokic921@gmail.com',
        nationality: 'Serbian',
        nationalID: '123349',
        country: 'Serbia',
     }, 
    {
        id:11,
        fullName: 'Olga Danilovic',
        email: 'olgadanilovic@gmail.com',
        nationality: 'Bosnian',
        nationalID: '64643',
        country: 'Bosnia and Herzegovina',
     }, 
       
]